# Generated by Django 4.2.3 on 2023-07-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player_category',
            old_name='player_cat_name',
            new_name='category',
        ),
    ]
